### ISSUE TITLE
InstanceNorm question

### ISSUE THREAD

**Issue by XernPLL** [jlian2/Improved-Voice-Conversion-with-Conditional-DSVAE#10]
Hi @jlian2,
I have a general question about model:
![image](https://user-images.githubusercontent.com/46560145/206420512-4503f3d3-a089-4b9e-8044-ca7d318fc19b.png)
As you said in paper that in encoder part you used knowledge from DSVAE (authors there used model on video frames -Conv2d (frames x batchsize, channels, width*height)). So in your case for audio it will be Conv1D on tensor: (batch x frame,channels, frequency), and after that you swap to (batch,channels,frame,frequency) for instancenorm2d?
On the other side in the Decoder part you said that you used AutoVC as template, but there authors use Conv1d on (batch, frequency, frame). So freq is like those channels. So if i want use there InstanceNorm2d i should create something like (batch,1,frame,frequency) from that?
As i did that i got bad results, so i think i have some misunderstand somewhere. Moreover when i use instancenorm without parametr affine=True my reconstrution loss even  doesnt decrease.
And there is a thing that my KLD content loss is always near zero. 

I will be glad if you correct me somewhere in my understanding.

**Comment by jlian2** [comment]
"So if i want use there InstanceNorm2d i should create something like (batch,1,frame,frequency) from that". Yes..
