### ISSUE TITLE
about speaker KLD loss

### ISSUE THREAD

**Issue by iehppp2010** [jlian2/Improved-Voice-Conversion-with-Conditional-DSVAE#2]
Hi, very great paper!
I've tried to implement this model. 
I try to use this model to do singing voice conversion, trained this model on my private singing dataset.

I have a question about the speaker kl-divergence loss function. When keep the speaker prior to be a Guassion prior, which is  zero mean and unit variance，should I make some constraint function or activation function(like LeakyReLU) to the output of the speaker mean-linear and variance-linear layer?
![image](https://user-images.githubusercontent.com/22955379/194735193-5c33d01e-5f1b-44a9-b5e6-bf2c6b128101.png)

Because during my model training, I found the speaker KLD loss couldn't get optimized(get smaller value), while the content KLD loss and reconstruction loss keeps going down.
![image](https://user-images.githubusercontent.com/22955379/194735305-cd5f72c6-c63c-4ea5-bd90-71f8e6b39715.png)

Looking for your response.
Much appreciated!

**Comment by jlian2** [comment]
Hi! For speaker prior, we found that 0.5 as std works better than 1. For mean linear, you don't need activation. But for std, you need either relu or softplus to make sure it is positive. Note that it is normal that KLD for speaker to goes up and KLD for content to goes down. This is reasonable in VAE training.

**Comment by iehppp2010** [comment]
> Hi! For speaker prior, we found that 0.5 as std works better than 1. For mean linear, you don't need activation. But for std, you need either relu or softplus to make sure it is positive. Note that it is normal that KLD for speaker to goes up and KLD for content to goes down. This is reasonable in VAE training.

OK, thanks very much for your quick response! 
I'll try your professional advice.

**Comment by spygaurad** [comment]
Hi @iehppp2010, i am also implementing this model for voice conversion on custom dataset. I am having problem implementing some of the components. Have you implemented the model, maybe i can reference it?
