### ISSUE TITLE
Clarifications regarding how is conditional prior modelled.

### ISSUE THREAD

**Issue by apoorvagnihotri** [jlian2/Improved-Voice-Conversion-with-Conditional-DSVAE#4]
![image](https://user-images.githubusercontent.com/22618985/196694317-ed264cea-5b99-48f8-9c8c-8c04941c3043.png)

@jlian2 Thanks for the amazing work! I am implementing the paper and wanted to understand the following questions regarding the part of the loss that focuses on content embeddings.

![equation](https://user-images.githubusercontent.com/22618985/196694964-2e036705-0714-4ecc-b116-bd3dd6dbaf47.png)
- How is this conditional prior modeled? As I understood (for C-DSVAW-WavLM), we have 50 different possibilities of _Y(X)_ for the whole dataset.

- For the case of DSVAE, pθ(zc) was modeled using a randomly initialized autoregressive LSTM. How was sampling happening for DSVAE using the autoregressive LSTMs? (usually, encoders output mean / std, and we sample, assuming them to be the parameters for a diagonal multivariate gaussian). I have drawn the LSTM and the two-layered NN. I don't understand how the sampling happens.
![image](https://user-images.githubusercontent.com/22618985/196702181-1ff9b627-20ad-4c22-873f-d2ee45d710a7.png)

- Now, for C-DSVAE, for a segment of audio (100 frames), we have 100 _Y(X)_'s corresponding to each frame. How are these content biases used to condition in the above prior model?

**Comment by jlian2** [comment]
For condition, we get and one hot vector and then concatenate at each frame for input.

For autoregressive LSTM, we suggest you to check (https://github.com/yatindandi/Disentangled-Sequential-Autoencoder)

**Comment by apoorvagnihotri** [comment]
Thanks, @jlian2. I checked out the links, and it's much clearer.

Here is a more detailed answer for people looking at this issue:

In DSVAE, the prior is modeled as a diagonal gaussian. Usually, an (unconditioned) autoregressive LSTM is used to generate the means and the variances of D_c (dim of content latent).  Next, the generated parameters are used to sample a vector which is passed into the LSTM for the next set of parameters.

![image](https://user-images.githubusercontent.com/22618985/197695672-8268fc50-5223-4ab5-b2c4-750dfc38f252.png)
 
In CDSVAE, instead of directly passing in the sampled vector, we concatenate it with a one-hot-encoded vector of length 50 corresponding to Y(X). This helps in conditioning the trajectory of the means and the variances obtained from the LSTM.

![image](https://user-images.githubusercontent.com/22618985/197696156-10fa82e9-4317-41ca-950e-9a13abc63ec5.png)
