### ISSUE TITLE
Additional Questions: Performance outside training dataset

### ISSUE THREAD

**Issue by apoorvagnihotri** [jlian2/Improved-Voice-Conversion-with-Conditional-DSVAE#6]
Hi @jlian2! Thanks for the great work. I had a question about the experimental setup for data usage (for training and testing). As I understand, the `VCTK` dataset has 111 people's recordings using two microphones (`mic1` and `mic2`). I had the following three questions:

- Did you use `mic1` or `mic2` from the VCTK dataset to train the model? Why choose one over the other?
- Did you use `mic1` or `mic2` from the VCTK dataset to test the model? Why choose one over the other?
- In case the same mics were used for training and testing, did you try testing on a different mic while experimenting?

**Comment by jlian2** [comment]
There is almost no diff between mic1 and mic2. You can randomly choose any one.
