### ISSUE TITLE
Clarification: Decoder pre/post nets?

### ISSUE THREAD

**Issue by apoorvagnihotri** [jlian2/Improved-Voice-Conversion-with-Conditional-DSVAE#8]
<img width="459" alt="image" src="https://user-images.githubusercontent.com/22618985/198320272-59ec2ef7-9316-43f2-8831-9251f18a56e8.png">

Hi @jlian2, how is the decoder able to create an image of shape (80 x 100) with the final layer in the PostNet? It seems to me that Prenet is capable of creating an image of the said shape instead.

I was assuming DecoderPrenet and DecoderPostnet are two parts of the whole decoder. Prenet comes first and Postnet is closer to the reconstructed image. But based on the decoder architecture, I don't understand how it can reconstruct the mels.

**Comment by jlian2** [comment]
Hi! We followed AutoVC. Please check that.
