### ISSUE TITLE
Clarification: Compute Requirements

### ISSUE THREAD

**Issue by apoorv-rai** [jlian2/Improved-Voice-Conversion-with-Conditional-DSVAE#9]
Hi @jlian2, thank you for your clarifications. I need additional help from you to understand the compute requirements that were required to train the model. Can you please answer the following questions in order for me to successfully reproduce the paper results?

- How many GPUs (and which) were used to train the model?
- How many epochs were used to train the final model?

**Comment by jlian2** [comment]
1 V100 should be enough. 100-200 epochs.
